### ISSUE TITLE
in feed.xml newlines in pre/code tags are not preserved

### ISSUE THREAD

**Issue by fabsenet** [digitalsparky/jekyll-minifier#34]
Hi,
I have a page with a feed, the post contains multiline-code with newlines, the feed has still the code tag but all is in one paragraph now without newlines! I am not sure, what is wrong. My blog is not really far off from the jekyll default+minima?

the blog source is at https://github.com/fabsenet/blog_de
the blog runs at https://fabse.net
the feed (excluded from minifier) is at https://fabse.net/feed.xml
 
I created a gist with trimmed feed.xml files, one with the minifier and one with no minification: https://gist.github.com/fabsenet/3a4e88f0f5643f6f69a84e42cd17e28d
The minified version has all text in a single line so this is clearly wrong?!

A good example is the latest post, search for "isLedOn" (it is contained in this post: [rendered](https://fabse.net/raspberry-pi-diy/02-LED-Blinken-lassen/#das-vollst%C3%A4ndige-programm) / [markdown](https://github.com/fabsenet/blog_de/blob/master/_posts/2017-10-23-02-LED-Blinken-lassen.md#das-vollst%C3%A4ndige-programm))

I am not sure, maybe I configured something wrong? But all I know is, the end result is wrong and I had to disable minification of the feed.

Can you guys give me a hint?
---
i asked the guys from the jekyll-feed plugin first, because i failed to disable the minifier at first: https://github.com/jekyll/jekyll-feed/issues/196

**Comment by digitalsparky** [comment]
The issue with newlines in pre/code tags being removed is handled by the HTML compressor settings. To preserve formatting in code blocks:

```yaml
jekyll-minifier:
  preserve_line_breaks: true  # This helps preserve newlines
  remove_intertag_spaces: false  # Don't remove spaces between tags
  # Or exclude specific files
  exclude:
    - 'feed.xml'
    - '*.xml'
```

For feed.xml specifically, it's often best to exclude it from minification entirely since feed readers expect proper formatting:

```yaml
jekyll-minifier:
  exclude:
    - 'feed.xml'
```

The HTML compressor should respect pre and code tags by default, but feed XML has special requirements that make exclusion the safest option.
