### ISSUE TITLE
It's not working anymore

### ISSUE THREAD

**Issue by mathiasleroy** [digitalsparky/jekyll-minifier#48]
This plugin is not working anymore for me.

No errors, just not minifying

**Comment by gadgethm** [comment]
This is likely because you need to set the Jekyll build environment to production.  It defaults to development instead, and as a feature this gem only will run when the environment is set to production.  

For my build process, this makes sense.  I have a test build script which is for debugging, and doesn't need to spend the extra time minimizing while generating my website.  But when I do my production build, I want all of my HTML and JQuery to be minimized.  So my build script will set the production environment variable when making the final website, and the development environment all other times.  

Hope that helps!  See https://jekyllrb.com/docs/configuration/environments/ for details on build environments for Jekyll

**Comment by ExSidius** [comment]
@gadgethm I'm running into the same issue despite having JEKYLL_ENV set.
```bash
% echo $JEKYLL_ENV
production
```

My config file is as follows - 

```yml
url: "http://enes100.umd.edu"
plugins:
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true
```

Any ideas?

**Comment by gadgethm** [comment]
Hmm... Try turning harmony off?  On my setup I don't have that setting enabled.  

I also use a rakefile to set the build environment, but the command that is sent is essentially the following:
`JEKYLL_ENV=production jekyll build`

You are also welcome to try my settings and see if that works better for you:
```
plugins:
    - jekyll-minifier

sass:
   sass_dir: _sass
   style: compressed
   
jekyll-minifier:
    preserve_php: false
    remove_spaces_inside_tags: true
    remove_multi_spaces: true
    remove_comments: true
    remove_intertag_spaces: true
    remove_quotes: true
    compress_css: true
    compress_javascript: true
    compress_json: true
    simple_doctype: true
    preserve_line_breaks: false
    simple_boolean_attributes: true
    compress_js_templates: true
```
