### ISSUE TITLE
Default config error with uglifier_args

### ISSUE THREAD

**Issue by simonkurka** [digitalsparky/jekyll-minifier#49]
with the
`uglifier_args:                    # Default: (empty)`
key set the build process fails with
`NoMethodError: undefined method `map' for nil:NilClass
  /usr/lib/ruby/gems/2.6.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:44:in `output_html'
  /usr/lib/ruby/gems/2.6.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:32:in `output_compressed'
  /usr/lib/ruby/gems/2.6.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:182:in `write'
...`

Commenting the uglifier_args line solves the issue.

I think this means the key is not empty by default?!

Tested with v0.1.10

**Comment by digitalsparky** [comment]
This appears to be a configuration issue. The error occurs when uglifier_args is set but empty.

**Fix:** Either remove the line entirely or provide a value:
```yaml
jekyll-minifier:
  # Option 1: Remove the line completely
  # uglifier_args:

  # Option 2: Provide an empty hash
  uglifier_args: {}

  # Option 3: Provide actual arguments
  uglifier_args:
    harmony: true
```

Note: In newer versions (v0.2.2+), the gem uses Terser instead of Uglifier, but uglifier_args is still supported for backward compatibility. The issue with nil values has been addressed in the latest version.
