### ISSUE TITLE
JSON+LD not getting compressed within HTML

### ISSUE THREAD

**Issue by aebrahim** [digitalsparky/jekyll-minifier#57]
In my HTML page, I've found that including JSON+LD is not getting compressed while other script tags are
```
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    // etc
}
</script>
```

My settings in `_config.yml` are
```
jekyll-minifier:
  uglifier_args:
    harmony: true
  remove_intertag_spaces: true
```

**Comment by digitalsparky** [comment]
Thanks for reporting this issue. JSON-LD script tags with type="application/ld+json" should be minified if JSON compression is enabled. The gem detects these script tags and applies JSON minification to their contents.

Make sure you have JSON compression enabled in your config:
```yaml
jekyll-minifier:
  compress_json: true  # This needs to be enabled
  compress_javascript: true
```

The gem specifically looks for script tags with type="application/ld+json" and applies JSON minification. If you're still experiencing this issue with the latest version (v0.2.2), please provide a minimal example and I'll investigate further.
